name: Create release

on:
  push:

jobs:
  akmod:
    runs-on: ubuntu-latest
    name: Build and publish rpm
    container:
      image: "registry.fedoraproject.org/fedora-minimal:39"
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    steps:
      - name: Prepare
        run: |
          echo 'max_parallel_downloads=20' >> /etc/dnf/dnf.conf
          dnf5 -y up
          dnf5 -y install fedora-packager rpmdevtools sudo
          useradd -m -G mock builduser
          echo 'builduser ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builduser

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          chown -R builduser:builduser ./
          bash entrypoint.sh vmware-workstation-kmod-common vmware-workstation-kmod

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: build-${{ env.VERSION }}
          path: /out/*

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: /out/*
          title: vmware-workstation-kmod-${{ env.VERSION }}
          automatic_release_tag: ${{ env.VERSION }}
